{% set name = "quantum-environ" %}
{% set version = "3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/environ-developers/Environ/archive/{{ name }}-{{ version }}.tar.gz
  sha256:

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - openmpi-mpifort
    - make
    - m4
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - pkg-config  # [osx]
    - wget
  host:
    - libblas
    - libcblas
    - openmpi
    - fftw
  run:
    - fftw
    - openmpi

about:
  home: http://www.quantum-environ.org
  license: GPL-2.0-only
  license_family: GPL
  license_file: License
  summary:

  description: |

  doc_url: https://environ.readthedocs.io/en/latest/
  dev_url: https://github.com/environ-developers/Environ

extra:
  recipe-maintainers:
    - eric-read
    - edan-bainglass
    - olivieroandreussi
